name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: cg-app-react:latest

      - name: Copy Docker image to remote host
        run: scp -o StrictHostKeyChecking=no -r cg-app-react:latest ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/bin/traefik
