name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: cg-app-react:latest

      - name: Save Docker image as tar file
        run: docker save -o cg-app-react.tar cg-app-react:latest

      - name: List files
        run: ls -la
      # - name: Copy Docker image to remote host
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     source: "cg-app-react:latest"
      #     target: "~/bin/traefik"
