name: Publish to my environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy to my environment
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ github.repository }} .

      - name: Save Docker image
        run: docker save -o docker.io/v-motta/cg-app-react .

      - name: List files
        run: ls -la

      - name: Copy file to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker.io/v-motta/cg-app-react"
          target: "~/bin/traefik"
