name: Publish to my environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy to my environment
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ github.repository }} .

      - name: Copy file to the server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sh ~/bin/traefik/run-cg-app-react.sh
