name: Publish to my environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy to my environment
    steps:
      - name: git-checkout
        uses: actions/checkout@v4.1.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and export image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          tags: cg-app-react:latest
          outputs: type=docker,dest=/tmp/cg-app-react.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: cg-app-react
          path: /tmp/cg-app-react.tar

  scp:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: List files
        run: ls -l

      - name: List more files
        run: ls -l /tmp
      # - name: Copy file to the server
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     port: ${{ secrets.SSH_PORT }}
      #     key: ${{ secrets.SSH_KEY }}
      #     source: "/tmp/cg-app-react.tar"
      #     target: "~/bin/traefik"
