name: Publish to my environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy to my environment
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ github.repository }} .

      - name: Copy file to the server
        run: scp -i ${{ secrets.SSH_KEY }} -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/your/server

      - name: Run command on the server
        run: ssh -i ${{ secrets.SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /path/to/your/server && docker-compose up -d'
