name: Publish to my environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy to my environment
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ github.repository }} .
