name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Build Docker image
        run: docker build -t cg-app-react:latest .

      - name: Save Docker image as tar file
        run: docker save -o cg-app-react.tar cg-app-react:latest

      - name: Copy Docker image to remote host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "cg-app-react.tar"
          target: "~/bin/traefik"
